const qs=new URLSearchParams(location.search), concept=qs.get('concept')||'compact', trigger=qs.get('trigger')||'replace';
document.body.classList.add(concept);if(qs.has('artboard'))document.body.classList.add('artboard');
const $=s=>document.querySelector(s), shades=[['jade','Jade Green','green-jade'],['aquamarine','Aquamarine Blue','blue-aquamarine'],['honey','Honey Hazel Brown','hazel-brown-honey'],['graphite','Graphite Dark Grey','dark-grey-graphite'],['bronze','Bronze Dark Brown','dark-brown-bronze'],['pearl','Pearl Grey','grey-pearl'],['sandstone','Sandstone Brown','brown-sandstone'],['sapphire','Sapphire Dark Blue','dark-blue-sapphire'],['turquoise','Turquoise Grey Blue','blue-green-turquoise'],['amber','Amber Brown','amber'],['emerald','Emerald Dark Green','emerald'],['olivine','Olivine Green Brown','olivine']];
const durations=[{name:'1-Day',pack:'5 pairs',price:319,compare:399,slug:'daily'},{name:'1-Month',pack:'1 pair',price:343,compare:429,slug:'monthly'},{name:'6-Months',pack:'1 pair',price:479,compare:599,slug:'6-months'}];
const powers=['0.00',...Array.from({length:23},(_,i)=>(-.5-i*.25).toFixed(2))];
let state={shade:'jade',duration:0,power:'',left:'',right:'',dual:false,qty:1,step:1},opener=null,cartCount=0;
function product(){return shades.find(s=>s[0]===state.shade)}
function pdp(s=product()){return `https://www.swati.com/products/${s[2]}-${durations[state.duration].slug}-lenses`}
function money(n){return n.toLocaleString('en-SE')+' kr'}
function packs(){return state.qty*(state.dual?2:1)}
function valid(){return state.dual?state.left!==''&&state.right!=='':state.power!==''}
function packText(){const n=packs(), pairs=n*(state.duration===0?5:1);return `${n} ${n===1?'pack':'packs'} · ${pairs} ${pairs===1?'pair':'pairs'}`}
$('#grid').innerHTML=shades.slice(0,4).map((s,i)=>`<article class="card"><div class="photo"><a href="https://www.swati.com/products/${s[2]}-daily-lenses"><img src="../assets/${s[0]}.png" alt="${s[1]} lenses on an eye"></a><div class="badges"><span class="badge">SAVE 20%</span>${i===0?'<span class="badge black">BESTSELLER</span>':''}</div>${trigger==='plus'?`<button class="plus-trigger" data-open="${s[0]}" aria-label="Quick add ${s[1]}">+</button>`:''}</div><div class="meta"><div><a href="https://www.swati.com/products/${s[2]}-daily-lenses"><strong>${s[1]}</strong></a><p>For Daily Use (5 Pairs)</p></div><div class="cardprice">319 kr<s>399 kr</s></div></div>${trigger==='split'?`<div class="splitactions"><a class="secondary" href="https://www.swati.com/products/${s[2]}-daily-lenses">SHOP NOW</a><button class="primary split-quick" data-open="${s[0]}" aria-label="Quick buy ${s[1]}" title="Quick buy">+</button></div>`:trigger==='plus'?`<a class="primary" style="display:flex;align-items:center;justify-content:center;text-decoration:none" href="https://www.swati.com/products/${s[2]}-daily-lenses">SHOP NOW</a>`:`<button class="primary" data-open="${s[0]}">QUICK ADD</button>`}</article>`).join('');
for(const id of ['power','left','right']){$('#'+id).innerHTML='<option value="">Select eye power</option>'+powers.map(v=>`<option value="${v}">${v==='0.00'?'0.00 · No correction':v}</option>`).join('');$('#'+id).onchange=e=>{state[id]=e.target.value;$('#error').hidden=true;update()}}
$('#duration-select').innerHTML=durations.map((d,i)=>`<option value="${i}">${d.name} (${d.pack})</option>`).join('');
$('#duration-select').onchange=e=>{state.duration=Number(e.target.value);if(state.duration===0&&shades.findIndex(s=>s[0]===state.shade)>8)state.shade='jade';state.power=state.left=state.right='';update()};
$('#durations').innerHTML=durations.map((d,i)=>`<button class="duration" data-duration="${i}" aria-pressed="${i===0}">${i===2?'<span class="choice-badge">Best choice</span>':''}${d.name}<small>${d.pack}</small></button>`).join('');
document.querySelectorAll('[data-duration]').forEach(b=>b.onclick=()=>{state.duration=Number(b.dataset.duration);if(state.duration===0&&shades.findIndex(s=>s[0]===state.shade)>8)state.shade='jade';state.power=state.left=state.right='';update()});
$('#shade').onchange=e=>{state.shade=e.target.value;state.power=state.left=state.right='';update()};
$('#dual').onchange=e=>{state.dual=e.target.checked;$('#error').hidden=true;update()};
$('#plus').onclick=()=>{state.qty++;update()};$('#minus').onclick=()=>{state.qty=Math.max(1,state.qty-1);update()};
function update(){const s=product(),d=durations[state.duration];$('#qtitle').textContent=s[1];$('#subline').textContent=`${d.name} · ${d.pack} per pack`;$('#unitprice').textContent=money(d.price);$('#compare').textContent=money(d.compare);for(const id of ['smallimage','largeimage']){const halfFace=concept==='guided'&&shades.indexOf(s)<9;$('#'+id).src=halfFace?`../assets/${s[0]}-half-face.jpg`:`../assets/${s[0]}.png`;$('#'+id).alt=halfFace?`${s[1]} half-face photograph`:s[1];$('#'+id).style.objectFit=halfFace||shades.indexOf(s)<4?'cover':'contain'}
$('#shade').innerHTML=shades.filter((s,i)=>state.duration!==0||i<9).map(s=>`<option value="${s[0]}">${s[1]}</option>`).join('');$('#shade').value=state.shade;$('#duration-select').value=state.duration;
document.querySelectorAll('[data-duration]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.duration)===state.duration));
$('#dual').checked=state.dual;$('.dualfields').hidden=!state.dual;$('#packnote').hidden=!state.dual;$('#power').closest('.field').hidden=state.dual;
for(const id of ['power','left','right'])$('#'+id).value=state[id];$('#qty').textContent=state.qty;$('#minus').disabled=state.qty===1;$('#qtylabel').textContent=state.dual?'Quantity per eye power':'Quantity';$('#qtyhelp').textContent=packText();$('#summary').textContent=packText();$('#total').textContent=money(d.price*packs());$('#details').href=pdp();
const guided=concept==='guided';$('.stepnav').hidden=!guided;$('#lensstep').hidden=guided&&state.step===2;$('#powerstep').hidden=guided&&state.step===1;$('.back').hidden=!(guided&&state.step===2);$('#step1tag').className=state.step===1?'active':'';$('#step2tag').className=state.step===2?'active':'';
$('#add').textContent=guided&&state.step===1?'CONTINUE TO EYE POWER →':valid()?`ADD TO BAG · ${money(d.price*packs())}`:'CHOOSE EYE POWER';$('#footerhint').textContent=guided&&state.step===1?'Step 1 of 2 · Choose your lenses.':state.dual?'Two packs per quantity — one for each eye power.':'Choose your options to add to bag.';
}
function open(shade,el){opener=el;state={shade,duration:0,power:'',left:'',right:'',dual:false,qty:1,step:1};$('#error').hidden=true;update();$('#quick').showModal();document.body.style.overflow='hidden';$('.close').focus()}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>open(b.dataset.open,b));
function close(d){d.close();document.body.style.overflow='';if(opener)opener.focus()}
document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>close(b.closest('dialog')));
for(const d of document.querySelectorAll('dialog')){d.addEventListener('cancel',()=>{document.body.style.overflow='';if(opener)opener.focus()});d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close(d)})}
$('.back').onclick=()=>{state.step=1;$('#error').hidden=true;update()};
$('#add').onclick=()=>{if(concept==='guided'&&state.step===1){state.step=2;update();$('#power').focus();return}if(!valid()){$('#error').hidden=false;$(state.dual?(state.left===''?'#left':'#right'):'#power').focus();return}cartCount+=packs();$('#count').textContent=cartCount;$('#receipt').innerHTML=`<b>${product()[1]}</b><br>${durations[state.duration].name} · ${packText()}<br>${state.dual?`Left ${state.left} / Right ${state.right}`:`Eye power ${state.power}`}<br><b>${money(durations[state.duration].price*packs())}</b>`;$('#quick').close();$('#success').showModal();$('#continue').focus()};
$('#continue').onclick=()=>close($('#success'));
if(qs.has('open')){open('jade',document.querySelector('[data-open]'));if(qs.get('state')==='dual'){state.dual=true;state.left='-1.00';state.right='-1.50';state.step=2;update()}else if(qs.get('state')==='ready'){state.power='0.00';state.step=2;update()}}
